### ISSUE TITLE
Conflict with SSM agent auto-update

### ISSUE THREAD

**Issue by hoegertn** [Hawxy/cdk-tailscale-bastion#22]
Hi,

I was wondering about the project status. Do you still actively maintain this project?

**Comment by Hawxy** [comment]
Hiya, yes I still do. There's just nothing to "update" at the moment unless something breaks/made obsolete.

**Comment by Hawxy** [comment]
I already included a sleep in the startup https://github.com/Hawxy/cdk-tailscale-bastion/blob/main/src/index.ts#L151 that was supposed to get around that. However, it appears this issue got worse in the last few months from what I can see on the AWS side.

Looks like the suggestion is to wrap the installation in a retry policy:
https://github.com/amazonlinux/amazon-linux-2023/issues/397
https://repost.aws/questions/QU_tj7NQl6ReKoG53zzEqYOw/amazon-linux-2023-issue-with-installing-packages-with-cloud-init

> Do you want to include that?

Unsure at the moment, I'm a bit concerned interrupting SSM's auto-update could potentially leave the host in a bad state.

**Comment by Hawxy** [comment]
Replacing https://github.com/Hawxy/cdk-tailscale-bastion/blob/main/src/index.ts#L152 with `until dnf -y install jq ; do sleep 10s ; done` should do the trick. Feel free to try it and put up a PR or I can take a look over the weekend.

**Comment by Hawxy** [comment]
Let me know if v2.1.3 resolves the issue.
